Traceback (most recent call last):
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\msipc\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
### Run this cell

from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mInvalidHeaderError[0m                        Traceback (most recent call last)
[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mnext[1;34m(self)[0m
[0;32m   2288[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2289[1;33m                 [0mtarinfo[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mtarinfo[0m[1;33m.[0m[0mfromtarfile[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2290[0m             [1;32mexcept[0m [0mEOFHeaderError[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mfromtarfile[1;34m(cls, tarfile)[0m
[0;32m   1094[0m         [0mbuf[0m [1;33m=[0m [0mtarfile[0m[1;33m.[0m[0mfileobj[0m[1;33m.[0m[0mread[0m[1;33m([0m[0mBLOCKSIZE[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1095[1;33m         [0mobj[0m [1;33m=[0m [0mcls[0m[1;33m.[0m[0mfrombuf[0m[1;33m([0m[0mbuf[0m[1;33m,[0m [0mtarfile[0m[1;33m.[0m[0mencoding[0m[1;33m,[0m [0mtarfile[0m[1;33m.[0m[0merrors[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1096[0m         [0mobj[0m[1;33m.[0m[0moffset[0m [1;33m=[0m [0mtarfile[0m[1;33m.[0m[0mfileobj[0m[1;33m.[0m[0mtell[0m[1;33m([0m[1;33m)[0m [1;33m-[0m [0mBLOCKSIZE[0m[1;33m[0m[1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mfrombuf[1;34m(cls, buf, encoding, errors)[0m
[0;32m   1038[0m         [1;32mif[0m [0mchksum[0m [1;32mnot[0m [1;32min[0m [0mcalc_chksums[0m[1;33m([0m[0mbuf[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1039[1;33m             [1;32mraise[0m [0mInvalidHeaderError[0m[1;33m([0m[1;34m"bad checksum"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1040[0m [1;33m[0m[0m

[1;31mInvalidHeaderError[0m: bad checksum

During handling of the above exception, another exception occurred:

[1;31mReadError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Roaming\Python\Python37\site-packages\torch\serialization.py[0m in [0;36m_load[1;34m(f, map_location, pickle_module, **pickle_load_args)[0m
[0;32m    554[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 555[1;33m             [1;32mreturn[0m [0mlegacy_load[0m[1;33m([0m[0mf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    556[0m         [1;32mexcept[0m [0mtarfile[0m[1;33m.[0m[0mTarError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\torch\serialization.py[0m in [0;36mlegacy_load[1;34m(f)[0m
[0;32m    465[0m [1;33m[0m[0m
[1;32m--> 466[1;33m         [1;32mwith[0m [0mclosing[0m[1;33m([0m[0mtarfile[0m[1;33m.[0m[0mopen[0m[1;33m([0m[0mfileobj[0m[1;33m=[0m[0mf[0m[1;33m,[0m [0mmode[0m[1;33m=[0m[1;34m'r:'[0m[1;33m,[0m [0mformat[0m[1;33m=[0m[0mtarfile[0m[1;33m.[0m[0mPAX_FORMAT[0m[1;33m)[0m[1;33m)[0m [1;32mas[0m [0mtar[0m[1;33m,[0m[0;31m [0m[0;31m\[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    467[0m                 [0mmkdtemp[0m[1;33m([0m[1;33m)[0m [1;32mas[0m [0mtmpdir[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mopen[1;34m(cls, name, mode, fileobj, bufsize, **kwargs)[0m
[0;32m   1592[0m                 [1;32mraise[0m [0mCompressionError[0m[1;33m([0m[1;34m"unknown compression type %r"[0m [1;33m%[0m [0mcomptype[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1593[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[0mname[0m[1;33m,[0m [0mfilemode[0m[1;33m,[0m [0mfileobj[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1594[0m [1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mtaropen[1;34m(cls, name, mode, fileobj, **kwargs)[0m
[0;32m   1622[0m             [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34m"mode must be 'r', 'a', 'w' or 'x'"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1623[1;33m         [1;32mreturn[0m [0mcls[0m[1;33m([0m[0mname[0m[1;33m,[0m [0mmode[0m[1;33m,[0m [0mfileobj[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1624[0m [1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36m__init__[1;34m(self, name, mode, fileobj, format, tarinfo, dereference, ignore_zeros, encoding, errors, pax_headers, debug, errorlevel, copybufsize)[0m
[0;32m   1485[0m                 [0mself[0m[1;33m.[0m[0mfirstmember[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1486[1;33m                 [0mself[0m[1;33m.[0m[0mfirstmember[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mnext[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1487[0m [1;33m[0m[0m

[1;32mD:\ProgramData\Anaconda3\lib\tarfile.py[0m in [0;36mnext[1;34m(self)[0m
[0;32m   2300[0m                 [1;32melif[0m [0mself[0m[1;33m.[0m[0moffset[0m [1;33m==[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2301[1;33m                     [1;32mraise[0m [0mReadError[0m[1;33m([0m[0mstr[0m[1;33m([0m[0me[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2302[0m             [1;32mexcept[0m [0mEmptyHeaderError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mReadError[0m: bad checksum

During handling of the above exception, another exception occurred:

[1;31mRuntimeError[0m                              Traceback (most recent call last)
[1;32m<ipython-input-2-5cde4022c60c>[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m                               ])
[0;32m      9[0m [1;31m# Download and load the training data[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 10[1;33m [0mtrainset[0m [1;33m=[0m [0mdatasets[0m[1;33m.[0m[0mMNIST[0m[1;33m([0m[1;34m'~/.pytorch/MNIST_data/'[0m[1;33m,[0m [0mdownload[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mtrain[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mtransform[0m[1;33m=[0m[0mtransform[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0mtrainloader[0m [1;33m=[0m [0mtorch[0m[1;33m.[0m[0mutils[0m[1;33m.[0m[0mdata[0m[1;33m.[0m[0mDataLoader[0m[1;33m([0m[0mtrainset[0m[1;33m,[0m [0mbatch_size[0m[1;33m=[0m[1;36m64[0m[1;33m,[0m [0mshuffle[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\torchvision\datasets\mnist.py[0m in [0;36m__init__[1;34m(self, root, train, transform, target_transform, download)[0m
[0;32m     76[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     77[0m             [0mdata_file[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mtest_file[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 78[1;33m         [0mself[0m[1;33m.[0m[0mdata[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mtargets[0m [1;33m=[0m [0mtorch[0m[1;33m.[0m[0mload[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mprocessed_folder[0m[1;33m,[0m [0mdata_file[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     79[0m [1;33m[0m[0m
[0;32m     80[0m     [1;32mdef[0m [0m__getitem__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mindex[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\torch\serialization.py[0m in [0;36mload[1;34m(f, map_location, pickle_module, **pickle_load_args)[0m
[0;32m    384[0m         [0mf[0m [1;33m=[0m [0mf[0m[1;33m.[0m[0mopen[0m[1;33m([0m[1;34m'rb'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    385[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 386[1;33m         [1;32mreturn[0m [0m_load[0m[1;33m([0m[0mf[0m[1;33m,[0m [0mmap_location[0m[1;33m,[0m [0mpickle_module[0m[1;33m,[0m [1;33m**[0m[0mpickle_load_args[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    387[0m     [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    388[0m         [1;32mif[0m [0mnew_fd[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\torch\serialization.py[0m in [0;36m_load[1;34m(f, map_location, pickle_module, **pickle_load_args)[0m
[0;32m    557[0m             [1;32mif[0m [0mzipfile[0m[1;33m.[0m[0mis_zipfile[0m[1;33m([0m[0mf[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    558[0m                 [1;31m# .zip is used for torch.jit.save and will throw an un-pickling error here[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 559[1;33m                 [1;32mraise[0m [0mRuntimeError[0m[1;33m([0m[1;34m"{} is a zip archive (did you mean to use torch.jit.load()?)"[0m[1;33m.[0m[0mformat[0m[1;33m([0m[0mf[0m[1;33m.[0m[0mname[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    560[0m             [1;31m# if not a tarfile, reset file offset and proceed[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    561[0m             [0mf[0m[1;33m.[0m[0mseek[0m[1;33m([0m[1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mRuntimeError[0m: C:\Users\msipc/.pytorch/MNIST_data/MNIST\processed\training.pt is a zip archive (did you mean to use torch.jit.load()?)
RuntimeError: C:\Users\msipc/.pytorch/MNIST_data/MNIST\processed\training.pt is a zip archive (did you mean to use torch.jit.load()?)

